# Generated by Django 6.0.6 on 2026-07-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden_pending_review', 'Hidden — pending moderation'), ('removed', 'Removed')], default='visible', max_length=25),
        ),
    ]
